ainize-team/ainize-js

- src/modules/service/depositService.ts
- src/modules/service/serviceBase.ts
다른건 type 딱히 정리할 것 없었고 changeBalance만 string -> INC_VALUE | DEC_VALUE 로 받도록 변경했습니다.
덤으로 changeBalance 에서 value에 type 넘기던 버그 발견하여 같이 수정했습니다.
> Refactor change balance type and fix value

- src/modules/service/useService.ts
dec, inc type 수정하면서 바뀐 부분 수정했습니다.
> fix: dec_value

- src/modules/app.ts
- src/types/type.ts
billing Config -> appBillingConfig serviceBillingConfig 로 분리하고 
appBillingConfig는 반드시 depositAddress와 default를, serviceBillingConfig는 반드시 minCost를 갖도록 룰 수정하였습니다.
> Add billingConfig and configOfService rule

- src/modules/app.ts
- src/modules/moduleBase.ts
- src/modules/service/depositService.ts
- src/modules/service/useService.ts
- src/modules/wallet.ts
모든 모듈에서 사용되는 getDefaultAccount를 protected로 baseModule 에 추가하고 기존 wallet module에서 사용되던 getDefaultAccount 함수는 getDefaultAddress 로 명칭 변경하였습니다.
> Add getDefaultAccount to baseModule and change wallet's getDefaultAccount to getDefaultAddress

- src/modules/admin.ts
- src/modules/app.ts
- src/modules/service.ts
- src/modules/service/useService.ts
checkCostAndBalance를 app으로 옮겼습니다
> refactor: checkCostAndBalance

- src/modules/app.ts
billingConfig rule 변경됨에 따라 수정했습니다.
> refactor: checkCost function

- src/modules/app.ts
- src/modules/moduleBase.ts
- src/modules/wallet.ts
- billing config 관련 룰 수정
- wallet.sendTxWithAddress 의 sendTransaction 변경
- handleTx Tx실패시 모든 op result 볼 수 있도록 변경.
> Fix write rules.

- src/constants.ts
- src/handlers/handler.ts
em.connect에서 timeout을 삭제했습니다.
callback 에서 this를 bind 했습니다.
Moduelbase 상속을 지웠습니다.
> fix: delete Timeout

- src/handlers/handler.ts
interval 지웠습니다.
disconnect callback async로 바꿨습니다.
> fix: delte interval

- src/ainize.ts
- src/internal.ts
> fix: add internal

- src/ainize.ts
model 생성 전, model이 존재하는지 체크하는 코드를 추가했습니다.
> feat: model check

- src/ainize.ts
- src/controllers/modelController.ts
- src/handlers/handler.ts
defaultAddresss 오타를 depositAddress로 바꿨습니다.
> fix: depositAddress

- src/handlers/handler.ts
- disconnectCb에 bind(this)를 추가했습니다.
- if문에 !를 뺐습니다.(기존에 반대로 작성)
> fix: handler

- src/ainize.ts
- src/controllers/modelController.ts
- src/handlers/handler.ts
- 기존의 subscribe를 subscribeResponse로 변경하고, 새로운 subscribeDeploy를 만들었습니다.
- deploy시 logincheck를 진행합니다.
- deploy에 eventHandler를 사용해, write가 완료되면 다음 프로세스로 넘어가도록 수정했습니다.
> feat: add eventHandler

- src/ainize.ts
apps/{appName}에서 apps/{appName}/status로 deploy subscribe path를 변경했습니다.
> fix: deploy listen path

- src/ainize.ts
- src/controllers/appController.ts
- src/controllers/serviceController.ts
- src/handlers/handler.ts
- src/service.ts
- src/types/type.ts
- src/utils/builder.ts
- tsconfig.json
Release branch 전 코드 정리합니다.
- 남아있는 jsdoc 제거
- require -> import (ts config 수정)
- 그 외 semicolon, spaces, comment style
> Code clean-up

- src/internal.ts
- src/types/type.ts
request data 를 value.prompt 에서 받는 것에서 value 자체를 받는것으로 변경하였습니다. 
prompt 뿐만 아니라 다양한 옵션을 넣을 수 있고, 이 데이터의 validation은 각자 서비스에서 알아서 하는 것으로 하면 될 것 같습니다.
> Fix request data format

- src/constants.ts
balance 0을 넣을 수 없는 문제를 해결하였습니다.
> Fix balance write rule

- src/controllers/serviceController.ts
request 시 prompt: requestData 가 아니라 request data 자체가 들어가도록 변경하였습니다.
> Remove prompt on request

- src/constants.ts
) 하나가 덜 붙어서 request 시에 write rule syntax error 발생하던 문제를 해결하였습니다.
> Fix request write rule syntax err

- src/constants.ts
- src/internal.ts
admin은 request 시 balance check 하지 않도록 write rule 추가하였습니다.
> Admin can use own service without balance check.

- src/constants.ts
- fix event handler url (https:// -> wss://)
> Fix event handler url

- package.json
- src/handlers/handler.ts
- yarn.lock
Change summary:
- Upgrade ain-js package version to v1.10.2
- Add isConnected() method for event channel connection
> Add isConnected() method for event channel connection

- README.md
> fix: uppercase

- README.md
fix: change model name to lowercase
> Develop -> main

- README.md
- add deploy example on readme
> refactor: readme deploy
