src/modules/app.ts
src/types/type.ts

app.create() 시에 service trigger는 세팅하지 않도록 변경하였습니다.
deposit url 은 serviceUrl/deposit 으로 고정하도록 변경하였습니다.
+
default set function들은 app에서만 사용되어 constant가 아니라 module 안 private method 로 이동하였습니다.

Remove service trigger in create

---

src/middlewares/middleware.ts
src/modules/admin.ts
src/modules/service/useService.ts
src/types/type.ts

reqeust type과
response type을 만들었습니다.

refactor: add req,res type

---

src/ainize.ts
src/controllers/modelController.ts
src/model.ts

- model class생성
- modelController skeleton생성. ainetwork와 통신하는 ain skeleton 구현 완료 후 작업 이어 하겠습니다.
- ainize에 model명령어 추가

feat: modelSkeleton

---

src/constants.ts
src/handlers/handler.ts
src/modules/admin.ts
src/modules/app.ts
src/modules/service.ts
src/modules/service/useService.ts
src/types/type.ts

ServiceName을 사용하는 코드들을 수정했습니다. 
rule 부분 확인 부탁드립니다.

refactor: delete serviceName

---

src/ainize.ts
src/constants.ts
src/controllers/appController.ts
src/types/type.ts

deploy config 추가하여 config data 로 app 생성하도록 변경하였습니다.
- config: modelName, billingConfig, serviceUrl (test deploy용. dev 이후 사라질 수 있음.)
- modelName == serviceName 입니다.
- deploy 함수에서 데이터를 받아 createApp으로 넘겨줍니다. 
setContainerStatus 추가하였습니다.
- deploy 시 createApp 에서 자동으로 RUNNING 상태로 기록합니다.
- stop 시 appController.setContainerStatus(modelName, ContainerStatus.STOP) 호출하면 됩니다.

Add deploy config and set contaner status

---

src/ainize.ts
src/controllers/modelController.ts

- ainize생성시 handler connect를 하도록 수정했습니다.
- isRunning 메소드 구현 후, 필요한 곳에 사용했습니다.

feat: connect

---

src/ainize.ts
src/controllers/appController.ts

Add ainize doc

---

.gitignore
src/controllers/modelController.ts
src/model.ts
src/types/type.ts

- model에 typedoc을 추가했습니다.
- creditHistory type을 생성했습니다.

feat: model typedoc

---

src/controllers/modelController.ts
src/model.ts

- isLoggedIn 체크를 modelController에서 하던 방법을 model에서 하는 방법으로 바꿨습니다.
- isAdmin 메소드를 구현했습니다.
- run, stop 메소드를 구현했습니다.

feat: model run and stop

---

README.md

Update module naming.

---

src/middlewares/middleware.ts

특정 api 안에서 trigger filter를 걸 수 있는 메소드를 추가했습니다.

specific api filter

---

src/controllers/serviceController.ts
src/service.ts

기존 isRunning 함수가 containerStatus.STOP 일 때 throw error 하도록 되어있었으나, 이 기능은 checkRunning 함수로 옮기고
boolean 을 반환하는 isRunning 으로 변경하였습니다.

Fix isRunning function returns boolean 

---

src/controllers/serviceController.ts
src/service.ts

Ainize request 시에 request data type 을 any 로 변경하였습니다.
이에 따라 string에 대해서만 비용 계산을 할 수 있는 현재의 calculateCost 함수는 일시적으로 deprecate 합니다.

Fix request data type.

---

src/controllers/serviceController.ts
src/service.ts

리퀘스트 키를 사용자가 지정할 수 있도록 변경합니다. 이는 blockchain 과 서비스 (db 등) 양 쪽에서 request key가 저장되어야 할 때 사용됩니다. 
리퀘스트 키 미입력 시 자동으로 timestamp가 들어갑니다.

Get req key from optional param

---

src/controllers/serviceController.ts

promise 안에서 throw Error 할 경우 외부에서 catch 하지 못하는 이슈가 있어 reject 를 통해 에러를 발생시키도록 변경하였습니다.

Throw error with reject in service.request

---

src/ainize.ts
src/controllers/serviceController.ts
src/internal.ts
src/middlewares/middleware.ts
src/utils/extractor.ts

- 데이터가 실제로 작성되었는지를 통해 blockchain trigger 검증 로직을 추가했습니다.
- deploy할 때 입력한 URL의 뒷부분에 '/'가 있으면 제거하는 코드를 추가했습니다.
- getData들의 구현체를 util의 extractor.ts로 이동시켰습니다. (middleware에서도 사용하기 위해서)
- checkRunning이 비동기로 작동해 코드가 실행된 후 에러가 발생하는 문제가 발생해 await을 추가했습니다.

blockchainTriggerFilter & deploy url check

---

package.json
src/ain.ts
src/ainize.ts
src/controllers/serviceController.ts
src/service.ts
yarn.lock

Ain Wallet Signer Login을 추가함에 따라 몇 가지 로직이 변경되었습니다.
- 기존 private key 로 로그인 하는 경우 DefaultSigner 를 통해 sendTransaction 합니다.
- loginWithSigner 함수를 이용하여 로그인 할 경우 AIN Wallet에서 AinWalletSigner 를 가져옵니다. (web 한정)

Add Signer login

---

src/handlers/handler.ts

Event handler 의 fallback 함수인 disconnectedCb 에서 address 유무 확인 시, address가 없으면 에러를 던지지 않도록 수정합니다.

Fix disconnect fallback 

---

package.json
src/ainize.ts
src/middlewares/middleware.ts

1.1.1-beta.1~3 의 테스트 완료된 수정사항들을 dev로 합칩니다.

Merge beta updates

---

package.json
src/ainize.ts
src/handlers/handler.ts
yarn.lock

Change summary:
- Add connection / disconnection callbacks params to login()
- Upgrade ain-js package to v1.12.0
Related issues:
- https://github.com/ainize-team/ainize-js/issues/125

Support connection / disconnection callback functions

---

package.json
src/ainize.ts
src/handlers/handler.ts
yarn.lock

Change summary:
- Support custom client id parameter in making connections with connect()
- Deprecate connection retry callback
- Upgrade ain-js package to v1.13.0
Related issues:
- https://github.com/ainblockchain/ain-blockchain/issues/1290
Related PRs:
- https://github.com/ainblockchain/ain-js/pull/205
- https://github.com/ainblockchain/ain-js/pull/206

Deprecate connection retry callback and support custom client id parameter

---

examples/charge.ts
examples/deploy.ts
examples/request.ts

- add example codes.
- charge.ts
- deploy.ts
- reqeust.ts

feat: add example codes
